server:
  port: 8080

spring:
  application:
    name: uaa-service
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/